import { task } from 'hardhat/config';
import { types } from 'hardhat/config';
import devAdapter from './devAdapter';
import devDeposit from './devDeposit';
import devMessage from './devMessage';
import devLaunch from './devLaunch';
import devClaim from './devClaim';
import transfer from './transfer';
import devSwapBuy from './devSwapBuy';
import devSwapSell from './devSwapSell';
import devMasterSwap from './devMasterSwap';
import devSlaveVerify from './devSlaveVerify';
import devMasterVerify from './devMasterVerify';
import eoalist from './eoalist';
import devSupply from './devSupply';
task('devSlaveVerify').setAction(devSlaveVerify);
task('devMasterVerify').setAction(devMasterVerify);
task('devAdapter').setAction(devAdapter);
task('devDeposit').setAction(devDeposit);
task('devMessage').setAction(devMessage).addOptionalParam<boolean>('message', 'show message').addOptionalParam('addr');
task('devLaunch').setAction(devLaunch);
task('devClaim').setAction(devClaim);
task('devSwapBuy').setAction(devSwapBuy);
task('devSwapSell').setAction(devSwapSell);
task('devMasterSwap').setAction(devMasterSwap);
task('transfer').setAction(transfer).addParam('target').addParam('amount');
task('eoalist').setAction(eoalist);
task('devSupply').setAction(devSupply);

